PROGRAM 1:A Water Jug Problem: You are given two jugs, a 4-gallon one and a 3-gallon one, a pump which has 
unlimited water which you can use to fill the jug, and the ground on which water may be poured. Neither 
jug has any measuring markings on it. How can you get exactly 2 gallons of water in the 4-gallon jug?
Implement using a python program.

In [6]:
def water_jug():
    jug1 = 0
    jug2 = 0

    print("Showing in the form of:(jug1 4G,jug2 3G)")
    jug2 = 3
    print(f"Filling 3 gallon fully: ({jug1}, {jug2})")

    jug1 += jug2
    jug2 = 0
    print(f"Pour 3gallon jug into 4 gallon jug: ({jug1}, {jug2})")

    jug2 = 3
    print(f"Filling 3 gallon jug again: ({jug1}, {jug2})")

    space_in_jug1 = 4 - jug1
    if jug2 <= space_in_jug1:
        jug1 += jug2
        jug2 = 0
    else:
        jug2 -= space_in_jug1
        jug1 = 4
    print(f"Pouring 3 gallon in 4 gallon until full: ({jug1}, {jug2})")

    jug1 = 0
    print(f"Emptying 4 gallon jug: ({jug1}, {jug2})")

    jug1 += jug2
    jug2 = 0
    print(f"Pouring remaining water from 3 gallon to 4 gallon: ({jug1}, {jug2})")

    return jug1

result = water_jug()
print(f"Final amount of water in Jug1: {result}")




Showing in the form of:(jug1 4G,jug2 3G)
Filling 3 gallon fully: (0, 3)
Pour 3gallon jug into 4 gallon jug: (3, 0)
Filling 3 gallon jug again: (3, 3)
Pouring 3 gallon in 4 gallon until full: (4, 2)
Emptying 4 gallon jug: (0, 2)
Pouring remaining water from 3 gallon to 4 gallon: (2, 0)
Final amount of water in Jug1: 2


Program 2: Implementation of Tic-Tac-Toe game using a python Program.

In [7]:
import numpy as np
import random
from time import sleep


def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)



def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after 2 move
[[0 2 0]
 [0 0 1]
 [0 0 0]]
Board after 3 move
[[0 2 0]
 [0 1 1]
 [0 0 0]]
Board after 4 move
[[0 2 0]
 [0 1 1]
 [2 0 0]]
Board after 5 move
[[0 2 0]
 [0 1 1]
 [2 0 1]]
Board after 6 move
[[0 2 0]
 [2 1 1]
 [2 0 1]]
Board after 7 move
[[0 2 0]
 [2 1 1]
 [2 1 1]]
Board after 8 move
[[2 2 0]
 [2 1 1]
 [2 1 1]]
Winner is: 2
